version: '3.8'

services:
  frontend:
    build:
      context: ./experimenthub
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./experimenthub:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - experimenthub-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/experimenthub
    depends_on:
      - db
    networks:
      - experimenthub-network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=experimenthub
    ports:
      - "5432:5432"
    networks:
      - experimenthub-network

networks:
  experimenthub-network:
    driver: bridge

volumes:
  postgres_data:
